device: cuda  # mps, cuda, cpu

model:
  model_id_or_path: Qwen/Qwen3-1.7B
  template: qwen

# MoE specific configuration
moe:
  num_experts: 3
  experts:
    - name: medical
      description: "Medical domain translation expert"
      task_type: "medical_translation"
    - name: en_vi
      description: "English to Vietnamese translation expert"
      task_type: "en_vi_translation"
    - name: vi_en
      description: "Vietnamese to English translation expert"
      task_type: "vi_en_translation"
  gating:
    hidden_size: 256
    dropout: 0.1
    load_balancing_weight: 0.01

lora:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM

training:
  max_steps: 3000
  output_dir: outputs/moe_model
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  num_train_epochs: 1
  logging_steps: 50
  save_steps: 500
  save_total_limit: 3
  logging_dir: logs/moe_training
  bf16: true
  fp16: false
  gradient_accumulation_steps: 2
  warmup_steps: 100
  learning_rate: 2e-4
  weight_decay: 0.01
  eval_strategy: steps
  eval_steps: 500
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  label_names: ["labels"]
  run_name: moe_medmt_run1

data:
  train_path: /home/users/sutd/1010047/VLSP-2025-MedMT/data/train.en.txt
  target_path: ./home/users/sutd/1010047/VLSP-2025-MedMT/data/train.vi.txt
  tokenized: ./home/users/sutd/1010047/VLSP-2025-MedMT/data/tokenized
  num_proc: 4
  max_length: 2048 # cuz max number of words (tokenized by space) is 400 

dataset:
  train_file: /home/users/sutd/1010047/VLSP-2025-MedMT/data/processed/train.jsonl
  val_file: /home/users/sutd/1010047/VLSP-2025-MedMT/data/processed/val.jsonl
  medical_file: /home/users/sutd/1010047/VLSP-2025-MedMT/data/processed/medical_train.jsonl
  en_vi_file: /home/users/sutd/1010047/VLSP-2025-MedMT/data/processed/en_vi_train.jsonl
  vi_en_file: /home/users/sutd/1010047/VLSP-2025-MedMT/data/processed/vi_en_train.jsonl


